groff
.TH MYSTRNCPY 3 "21 September 2025" "Version 0.4.1" "Library Functions"
.SH NAME
mystrncpy \- Copies at most n characters from source to destination
.SH SYNOPSIS
int mystrncpy(char *dest, const char *src, int n);
.SH DESCRIPTION
mystrncpy copies up to `n` characters from the string `src` into `dest`.
If `src` is shorter than `n`, only the characters in `src` are copied.
.SH AUTHOR
Maryam Majid  <your_email@example.com>

