
groff
.TH MYSTRLEN 3 "21 September 2025" "Version 0.4.1" "Library Functions"
.SH NAME
mystrlen \- Returns the length of a string
.SH SYNOPSIS
int mystrlen(const char *s);
.SH DESCRIPTION
mystrlen takes a null-terminated string `s` as input and returns the number of characters
in the string, excluding the null terminator.
.SH AUTHOR
Maryam Majid <your_email@example.com>

