groff
.TH MYSTRCPY 3 "21 September 2025" "Version 0.4.1" "Library Functions"
.SH NAME
mystrcpy \- Copies a string from source to destination
.SH SYNOPSIS
int mystrcpy(char *dest, const char *src);
.SH DESCRIPTION
mystrcpy copies the string pointed to by `src` into the buffer pointed to by `dest`.
It returns the number of characters copied, excluding the null terminator.
.SH AUTHOR
Maryam Majid  <your_email@example.com>

